# Generated by Django 5.2.7 on 2026-03-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING_PAYMENT', 'PENDING_PAYMENT'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
            ],
        ),
    ]
